# Step 1: Create the word lists
NAWL = [
    "abdominal", "absorb", "absorption", "accelerate", "acceleration", "accent", 
    "accumulate", "accumulation", "accuracy", "accurately", "acid", "acidic", 
    "activate", "actively", "acute", "adaptation", "adaptive", "adjacent", 
    "admission", "adolescent", "adverse", "aerosol", "aesthetic", "affirm", 
    "afterward", "aggregate", "agriculture", "airplane", "algebra", "algorithm", 
    "alien", "alliance", "allocate", "allocation", "altitude", "aluminum", 
    "amino", "amongst", "amplitude", "analogy", "ancestor", "anthropology", 
    "anti", "antibiotic", "antibody", "antiquity", "appendix", "applause", 
    "apple", "approximate", "approximation", "arbitrary", "archaeology", 
    "architect", "array", "arrow", "articulate", "artifact", "artificial", 
    "artistic", "artwork", "aspect", "assembly", "assert", "assignment", 
    "athletic", "atom", "atomic", "auction", "audio", "audit", "authority", 
    "autonomy", "availability", "axiom", "axis", "backward", "bacteria", 
    "bacterial", "bang", "bargain", "barrel", "basin", "bat", "beam", 
    "behavioral", "bilingual", "binary", "biodiversity", "biologist", "biology", 
    "bizarre", "blank", "bleed", "bodily", "bonus", "bound", "bracket", 
    "breakdown", "broadly", "bubble", "bucket", "bulk", "bullet", "bundle", 
    "calcium", "calculation", "calculator", "calculus", "campus", "capillary", 
    "capitalism", "capitalist", "carrier", "cattle", "censor", "characterization", 
    "cheat", "cheer", "chemistry", "chemotherapy", "chess", "chloride", 
    "chromosome", "chronic", "chunk", "cinema", "circa", "circulate", 
    "circulation", "civilization", "clarify", "classification", "classify", 
    "classroom", "clay", "clever", "client", "clinic", "clip", "clone", 
    "closure", "clue", "coefficient", "cognitive", "coherent", "collective", 
    "colonial", "colony", "comma", "commentary", "commodity", "commonly", 
    "communicative", "communist", "compact", "comparable", "comparative", 
    "compensate", "competence", "competent", "complement", "complication", 
    "comply", "composer", "composite", "comprehension", "computation", 
    "conceive", "conception", "conceptual", "conditional", "conduction", 
    "cone", "configuration", "confine", "confound", "congruent", "connector", 
    "connotation", "conscious", "consciousness", "consensus", "consent", 
    "conservation", "conserve", "consonant", "constitution", "constrain", 
    "consultation", "consumption", "container", "continent", "continuity", 
    "contour", "contradict", "contradiction", "contradictory", "contrary", 
    "controversy", "converge", "convergence", "coordinate", "coordination", 
    "cord", "coronary", "corpus", "correction", "correctly", "correlate", 
    "correlation", "correspondence", "corruption", "cortex", "credibility", 
    "critically", "critique", "crude", "crystal", "cue", "cure", "curriculum", 
    "cyclic", "cylinder", "damp", "deadline", "decay", "deceive", "defect", 
    "deficiency", "definite", "deflection", "degrade", "deliberately", "delta", 
    "demonstrator", "denominator", "denote", "dense", "dependence", "depict", 
    "derivative", "descendent", "descriptor", "destination", "detection", 
    "developmental", "deviation", "diagnose", "diagnosis", "diagnostic", 
    "diagram", "dialect", "diameter", "diary", "dictate", "dictionary", 
    "differential", "differentiate", "differentiation", "diffusion", "dilemma", 
    "dilute", "dimensional", "dioxide", "directive", "disability", "disadvantage", 
    "discharge", "discourse", "discrete", "discrimination", "displacement", 
    "dissection", "dissertation", "dissolve", "distribution", "disturbance", 
    "diverse", "domain", "dominance", "dominant", "domination", "donor", 
    "dose", "drain", "drift", "duration", "dye", "dynamic", "ecological", 
    "ecology", "economically", "economist", "effectiveness", "elaborate", 
    "elastic", "elasticity", "electron", "elementary", "elevate", "elevation", 
    "elimination", "elite", "embed", "emergence", "emission", "emit", 
    "emperor", "empirical", "encode", "enforcement", "enormously", "entity", 
    "entrant", "enzyme", "epidemic", "epidemiology", "equality", "equilibrium", 
    "equivalence", "erase", "essence", "essentially", "estimation", "ethical", 
    "ethics", "evident", "evolutionary", "ex", "execute", "execution", "exit", 
    "expertise", "explicit", "explicitly", "exploit", "exponential", "fabric", 
    "facet", "facilitate", "factorial", "faculty", "fatigue", "feedback", 
    "fertility", "fetal", "fever", "fiber", "fin", "finite", "flesh", 
    "flexibility", "flip", "fluid", "flux", "footnote", "formally", 
    "formulation", "forum", "fossil", "fraction", "fracture", "freely", 
    "friction", "fringe", "fundamentally", "fungus", "fusion", "gauge", 
    "generalization", "generalize", "genetically", "genetics", "ghost", 
    "globalization", "goat", "goodness", "goods", "gradient", "gram", 
    "grammatical", "graph", "grasp", "gravity", "grid", "gross", "gut", 
    "habitat", "halfway", "handout", "harvest", "hawk", "headquarter", 
    "hedge", "helix", "hepatitis", "herbicide", "hierarchy", "hip", 
    "historically", "homework", "horizon", "horizontal", "hormone", 
    "hydrogen", "identical", "identification", "ideology", "illusion", 
    "immune", "impact", "implicit", "importantly", "impulse", "incidence", 
    "incline", "inclusion", "incredible", "incredibly", "incumbent", 
    "independently", "indicator", "indifference", "indigenous", "indirect", 
    "individually", "induce", "induction", "industrialization", "industrialize", 
    "inequality", "inevitably", "infect", "infectious", "inference", 
    "inferior", "infinite", "infinity", "influential", "informal", "inhibit", 
    "inhibition", "initiate", "initiation", "inject", "injection", "innate", 
    "insect", "insert", "instability", "instinct", "integral", "integration", 
    "intensity", "intensive", "interact", "interestingly", "interface", 
    "interfere", "intermediate", "interrupt", "interval", "intervene", 
    "interviewer", "invade", "invasion", "inversion", "invert", "ion", 
    "irrelevant", "irrigation", "jazz", "junior", "justification", "kidney", 
    "kilometer", "lab", "lateral", "layout", "leaf", "lecturer", "legend", "legitimate", "leisure", "lever", 
    "lexical", "liable", "lifestyle", "lifetime", "likelihood", "likewise", 
    "limb", "linear", "linguistic", "linguistics", "liter", "liver", "locally", 
    "locus", "logical", "longitudinal", "loop", "lump", "lung", "machinery", 
    "magnetic", "magnitude", "mall", "manipulate", "manipulation", "manual", 
    "manuscript", "marble", "marginal", "marker", "marrow", "maternal", 
    "mathematical", "matrix", "maximize", "meaningful", "mechanic", 
    "mechanical", "media", "mediate", "membrane", "memorize", "mentor", 
    "mercury", "merge", "messenger", "metabolism", "metaphor", "methodology", 
    "micro", "mid", "migrate", "migration", "millimeter", "mineral", "minimal", 
    "minimize", "minus", "missile", "mobility", "modification", "mole", 
    "molecular", "molecule", "momentum", "monetary", "monkey", "monopoly", 
    "morality", "morphological", "morphology", "mortality", "motif", "motive", 
    "multi", "multinational", "multiply", "mutation", "myth", "naked", "namely", 
    "nasty", "nationalism", "neat", "necessity", "neo", "nest", "neural", 
    "neuron", "neutral", "nicely", "niche", "nitrogen", "noble", "node", "noisy", 
    "nominal", "non", "nonetheless", "nonlinear", "norm", "notation", "novice", 
    "nucleus", "null", "numerical", "nutrient", "objection", "obscure", 
    "observer", "obtain", "occupation", "occurrence", "offspring", "onset", 
    "onwards", "optical", "optimal", "optimum", "oral", "organ", "organism", 
    "orient", "orientation", "oscillation", "outer", "outlet", "overhead", 
    "overlap", "overview", "oxidize", "oxygen", "painful", "par", "paradigm", 
    "paradox", "parameter", "parcel", "pardon", "parental", "parenthesis", 
    "partial", "partially", "particle", "partition", "pathway", "peasant", 
    "periodic", "peripheral", "pest", "pesticide", "phenomenal", "philosopher", 
    "philosophical", "phonological", "phosphate", "photographic", "physically", 
    "physician", "physics", "physiological", "pi", "planner", "plantation", 
    "plausible", "plug", "plural", "polar", "pole", "politically", "portfolio", 
    "portray", "portrayal", "positively", "poster", "postgraduate", "potassium", 
    "powder", "practitioner", "pragmatic", "pre", "precede", "precipitate", 
    "precipitation", "predator", "prediction", "predominantly", "prejudice", 
    "preliminary", "presume", "prevalence", "prey", "primer", "primitive", 
    "probe", "problematic", "processor", "productive", "productivity", 
    "profound", "progression", "progressive", "projection", "prominent", 
    "pronounce", "proposition", "protocol", "proton", "psychiatric", 
    "psychologist", "psychology", "publish", "pulse", "punch", "punish", 
    "punishment", "purely", "puzzle", "qualitative", "quantitative", "quantum", 
    "questionnaire", "quiz", "quotation", "rack", "radar", "radiation", "radius", 
    "rainfall", "randomize", "randomly", "rational", "rationality", "ray", 
    "reactive", "reactor", "readily", "realism", "realistic", "realm", 
    "receptor", "recipe", "reconstruct", "regime", "regression", 
    "rehabilitation", "reinforce", "rejection", "reliability", "render", 
    "repertoire", "replacement", "replicate", "replication", "reproduce", 
    "reproduction", "republic", "resemble", "reservoir", "residual", "residue", 
    "resistant", "respiratory", "retrieve", "revolutionary", "rewrite", 
    "rhetoric", "rhythm", "ridiculous", "ritual", "robot", "rope", "rotate", 
    "rotation", "rub", "ruler", "scatter", "scenario", "scholarship", 
    "scripture", "scroll", "secrete", "sediment", "selective", "semantic", 
    "semester", "semi", "seminar", "sensation", "sensible", "sensitivity", 
    "sensory", "separately", "separation", "sexuality", "shallow", "shortly", 
    "shuttle", "similarity", "simplify", "simulate", "simulation", 
    "simultaneously", "sin", "singular", "sketch", "skip", "slab", "slash", 
    "slavery", "slot", "snake", "sneeze", "sniff", "socialize", "socially", 
    "sodium", "soluble", "solute", "solvent", "sometime", "sophisticate", 
    "span", "spatial", "specialty", "specification", "specimen", "spectrum", 
    "sperm", "sphere", "splice", "sponsorship", "spontaneous", "spray", 
    "stabilize", "stack", "stadium", "stance", "standardize", "static", 
    "statistical", "statistically", "statistics", "stereotype", "stimulus", 
    "straightforward", "strand", "strategic", "strictly", "stripe", "sub", 
    "subjective", "subset", "substitution", "substrate", "subtle", "subtract", 
    "sufficiently", "suicide", "super", "superior", "supposedly", "surgeon", 
    "surgical", "surplus", "susceptible", "sustainable", "swap", "swell", 
    "sword", "syllable", "syllabus", "symbolic", "syndrome", "syntactic", 
    "syntax", "synthesis", "synthetic", "systematic", "tech", "technically", 
    "temporal", "tempt", "tense", "terminal", "terminology", "terribly", 
    "textbook", "theorem", "theorist", "thereby", "thermal", "thesis", 
    "thickness", "thread", "threshold", "thumb", "tolerance", "ton", "toxic", 
    "tract", "traditionally", "trait", "trajectory", "trans", "transaction", 
    "transcribe", "transcription", "transformation", "translation", 
    "transmission", "transmit", "transparency", "transplant", "trauma", 
    "treaty", "tremendous", "triangle", "tribe", "tricky", "trivial", 
    "tropical", "tumor", "turbulent", "tutor", "ultimate", "undergraduate", 
    "undermine", "underneath", "unemployed", "unify", "unintelligible", "unity", 
    "unstable", "uplift", "upward", "urine", "usage", "utility", "utilize", 
    "utterance", "vague", "valid", "validity", "valve", "variability", 
    "variance", "variant", "vector", "vegetation", "vein", "velocity", "verbal", 
    "vertical", "viable", "virtue", "vitamin", "vocabulary", "volition", 
    "vowel", "watershed", "wavelength", "weave", "wheat", "whereby", "whichever", 
    "whoever", "widespread", "wisdom", "workshop", "yeast"
]
NGSL = [
    "accident", "habit", "activity", "add", "adjust", "administration", "advocate", "analyst", "arrival", "highlight", "button", "appearance", "application", "apply", "as", "argument", "arrange", "arrangement", "hunt", "art", "characterize", 
    "assessment", "asset", "back", "associate", "atmosphere", "attitude", "illustrate", "audience", "author", "impose", "band", "bar", "basically", "bedroom", "belief", "bind", "birth", "bomb", "bond", "border", "competitor", "incident", "intelligence", 
    "branch", "brand", "build", "business", "bridge", "coverage", "crew", "kick", "kiss", "dependent", "campaign", "latter", "lock", "cent", "certainly", "chain", "channel", "characteristic", "milk", "color", "origin", "church", "drag", "civil", "proportion", 
    "reject", "clothes", "course", "colleague", "formula", "combination", "foundation", "lip", "comment", "commission", "commitment", "relief", "complain", "component", "concentrate", "condition", "margin", "content", "contract", "contribute", "pace", "corner", 
    "reputation", "shoulder", "perception", "similarly", "crime", "supporter", "symbol", "cultural", "sky", "cream", "evolution", "example", "decrease", "exhaust", "soul", "delay", "specifically", "demonstrate", "extract", "talent", "desire", "destroy", "direction",
    "distinction", "division", "doctor", "domestic", "iron", "economy", "editor", "elect", "knee", "stem", "engineer", "entirely", "wage", "wheel", "escape", "winner", "estimate", "appointment", "here", "examine", "breakfast", "excite", "however", "breast",
    "capture", "celebrate", "expense", "explore", "extend", "childhood", "fairly", "farmer", "fear", "feed", "closely", "file", "angle", "flower", "attribute", "command", "consistent", "core", "frame", "bowl", "crop", "gain", "debt", "generally", "last", 
    "exhibition", "graduate", "leave", "liability", "gun", "life", "hall", "hang", "line", "cake", "hire", "historical", "host", "hotel", "fellow", "many", "currency", "hurt", "ice", "gene", "identity", "curve", "image", "imagine", "modify", "month", "income",
    "indicate", "industrial", "guard", "insist", "instrument", "depression", "off", "investor", "on", "entrance", "order", "accommodation", "flood", "assistant", "party", "label", "lady", "boss", "past", "forecast", "jacket", "lawyer", "plan", "lesson", 
    "bottle", "license", "chemical", "delight", "engine", "loan", "locate", "expectation", "gentleman", "journalist", "lake", "room", "mass", "master", "meal", "landscape", "set", "miss", "mistake", "model", "mirror", "mouse", "moral", "morning", 
    "participant", "passenger", "narrow", "negative", "neither", "net", "nevertheless", "musician", "noise", "none", "opponent", "occasion", "odd", "plate", "snap", "onto", "plot", "oppose", "producer", "organize", "phenomenon", "original", "stay", 
    "package", "pair", "shadow", "subject", "singer", "such", "statistic", "substance", "summary", "permit", "protein", "teenager", "photograph", "throat", "tourism", "plenty", "tower", "transition", "population", "trap", "practical", "presence", 
    "president", "principal", "principle", "print", "prison", "turn", "professional", "property", "vegetable", "row", "provision", "sheet", "race", "rank", "ready", "recommendation", "water", "reflect", "region", "shirt", "relation", "relax", "release", 
    "relevant", "which", "rely", "voter", "represent", "witness", "would", "ring", "write", "joint", "reserve", "pupil", "sample", "scientist", "seat", "secret", "secretary", "security", "seriously", "session", "pitch", "second", "hour", "fault", "shoe", 
    "shot", "god", "sight", "sign", "signal", "muscle", "enterprise", "site", "skin", "company", "slowly", "smile", "symptom", "revolution", "amendment", "carbon", "square", "cousin", "insight", "orange", "tournament", "bin", "stock", "strongly", "structure", 
    "studio", "style", "emotion", "mother", "succeed", "slice", "disk", "resolution", "suspect", "switch", "negotiation", "welfare", "taste", "tear", "technology", "family", "television", "temperature", "theory", "species", "dozen", "tie", "phrase", "tool", 
    "touch", "gesture", "city", "tradition", "bell", "disorder", "troop", "true", "chicken", "union", "user", "variety", "convention", "victim", "violence", "lot", "truck", "wake", "mail", "wear", "weather", "wed", "west", "agenda", "gaze", "far", "counter",
    "passage", "wood", "heavily", "much", "writer", "aircraft", "motor", "ability", "cloud", "leather", "inch", "above", "abortion", "motion", "web", "absolutely", "minority", "mechanism", "accept", "edition", "access", "trail", "circle", "accord",
    "account", "day", "era", "achieve", "chairman", "manufacturer", "acquire", "server", "pilot", "act", "action", "active", "actor", "actual", "lover", "ad", "refugee", "addition", "additional", "address", "scholar", "researcher", "terrorist",
    "admit", "adopt", "adult", "advance", "advantage", "servant", "advertise", "advice", "critic", "rival", "affair", "affect", "afford", "afraid", "advertisement", "afternoon", "log", "draft", "drama", "agency", "laboratory", "agent", "pub",
    "shelter", "agree", "agreement", "resort", "ahead", "aid", "aim", "air", "end", "elderly", "platform", "panel", "rose", "chamber", "restriction", "storage", "clause", "uniform", "website", "alone", "dish", "cooperation", "cat", "adjustment",
    "seed", "cigarette", "alternative", "tip", "chip", "coin", "amaze", "gap", "magic", "amount", "analysis", "mission", "area", "premise", "equation", "faith", "animal", "announce", "castle", "annual", "bias", "stake", "fool", "emergency",
    "chocolate", "democracy", "anybody", "column", "anyone", "professor", "anyway", "apart", "toy", "it", "absence", "apparently", "appeal", "appear", "port", "appreciate", "approach", "appropriate", "metal", "approve", "car", "bike",
    "plastic", "argue", "virus", "arm", "army", "child", "arrest", "arrive", "article", "artist", "logic", "blog", "victory", "assess", "fence", "noun", "poem", "association", "assume", "index", "journal", "cheese", "initiative",
    "vision", "capable", "attack", "attempt", "attend", "mobile", "attention", "attract", "efficient", "over", "suitable", "recognition", "luck", "available", "average", "avoid", "award", "aware", "report", "participation",
    "survival", "baby", "background", "limitation", "opposition", "bag", "balance", "ball", "expansion", "bank", "acquisition", "presentation", "assistance", "basic", "basis", "announcement", "battle", "creation", "beach",
    "bear", "beat", "beautiful", "registration", "development", "involvement", "bed", "legislation", "infection", "transportation", "laughter", "behavior", "behind", "sanction", "entertainment", "belong", "below", "venture",
    "game", "work", "benefit", "real", "woman", "privilege", "anxious", "beyond", "subsequently", "breath", "beer", "universe", "bill", "world", "membership", "bird", "household", "virtually", "black", "barely", "though",
    "expenditure", "block", "blood", "output", "blow", "blue", "board", "boat", "body", "quantity", "excess", "story", "man", "compromise", "discount", "layer", "deficit", "rat", "bottom", "country", "box", "boy", "brain",
    "slope", "hill", "county", "contest", "adventure", "brief", "adviser", "bright", "interpretation", "wound", "broad", "bid", "brother", "settlement", "sequence", "budget", "creature", "hell", "burn", "unlike",
    "neighborhood", "bus", "busy", "shade", "territory", "desert", "zone", "harbor", "province", "dispute", "camera", "camp", "approximately", "naturally", "cancer", "even", "what", "league", "capacity", "capital",
    "along", "ago", "card", "before", "career", "soon", "carefully", "always", "carry", "young", "cash", "whenever", "ever", "originally", "meanwhile", "catch", "category", "during", "then", "cell", "initially", 
    "central", "century", "now", "certain", "chair", "nowadays", "challenge", "regularly", "fascinate", "moderate", "chance", "out", "chapter", "character", "charge", "tail", "storm", "bread", "belt", "truly", 
    "cheap", "check", "liquid", "framework", "firstly", "aggressive", "chief", "equivalent", "mature", "smart", "choice", "choose", "prompt", "circumstance", "keen", "citizen", "native", "eastern", "claim", "in",
    "no", "contemporary", "clean", "poverty", "clearly", "genuine", "climb", "record", "clock", "vast", "idea", "of", "club", "coach", "historic", "extraordinary", "corporation", "code", "coffee", "large", "cold",
    "hand", "collect", "collection", "college", "fiction", "combine", "album", "mystery", "comfortable", "commercial", "commit", "committee", "common", "uncle", "communication", "community", "house", "compare", 
    "comparison", "office", "school", "competition", "publisher", "personally", "complete", "completely", "complex", "via", "widely", "beside", "flexible", "observation", "pleasant", "controversial", "fortune",
    "effect", "computer", "infant", "concept", "random", "concert", "conclude", "conclusion", "distinct", "conduct", "confidence", "coat", "confirm", "conflict", "money", "information", "connect", "connection", 
    "consequence", "gray", "yellow", "carpet", "first", "consideration", "consist", "western", "airline", "absolute", "whole", "altogether", "construction", "exact", "all", "literary", "consumer", "contact", 
    "contain", "urban", "royal", "context", "institutional", "presumably", "contrast", "contribution", "agricultural", "organic", "political", "classical", "conversation", "sexual", "convince", "cook", "cool", 
    "public", "abstract", "copy", "corporate", "retail", "correct", "inner", "mental", "genetic", "online", "council", "ethnic", "count", "tank", "inflation", "temporary", "couple", "court", "dialog", "cover", "accurate", "free", "policy", "envelope", 
    "roof", "wet", "bloody", "offense", "festival", "credit", "hook", "crisis", "critical", "destruction", "coal", "cross", "crowd", "pot", "cry", "culture", "cup", "profile", "current", "currently", "reliable", "architecture", "customer", "cut", "cycle", 
    "although", "daily", "damage", "explanation", "dance", "danger", "dangerous", "criteria", "dark", "filter", "data", "unusual", "date", "daughter", "hard", "dead", "pollution", "dear", "death", "debate", "decade", "mess", "decision", "depth", "decline", 
    "deep", "height", "phase", "defense", "injure", "define", "definitely", "definition", "degree", "deliver", "delivery", "demand", "helpful", "universal", "voluntary", "violent", "deny", "department", "depend", "immediate", "chart", "alcohol", "fall", 
    "describe", "description", "while", "whilst", "design", "sensitive", "desk", "despite", "visible", "detail", "soft", "apparent", "determine", "clear", "potato", "device", "impression", "mood", "die", "electricity", "adequate", "difference", "enough", 
    "each", "difficult", "difficulty", "everywhere", "test", "case", "dinner", "direct", "directly", "director", "good", "stimulate", "numerous", "distant", "silver", "veteran", "consultant", "discover", "reason", "discuss", "discussion", "disease", 
    "demonstration", "extension", "further", "giant", "display", "crucial", "distance", "remote", "sheep", "pig", "dad", "district", "anxiety", "motivation", "divide", "tension", "joy", "document", "dog", "dollar", "friendship", "door", "double", 
    "doubt", "hunger", "concern", "grateful", "ashamed", "confident", "uncertainty", "draw", "dream", "dress", "drink", "sad", "driver", "drop", "drug", "dry", "due", "she", "ultimately", "duty", "dust", "solid", "steady", "earn", "earth", "start", 
    "easily", "term", "shelf", "easy", "eat", "economic", "edge", "conventional", "fruit", "boot", "education", "because", "forever", "effective", "per", "so", "why", "effort", "egg", "sir", "format", "election", "lucky", "hence", "through", "element", 
    "across", "else", "since", "e-mail", "face", "tennis", "emerge", "golf", "preparation", "present", "sale", "down", "employ", "employee", "into", "alright", "empty", "enable", "honest", "encourage", "sand", "more", "energy", "engage", "tall", "enjoy", 
    "empire", "tune", "ensure", "enter", "government", "jury", "personnel", "entire", "bunch", "pile", "type", "environment", "environmental", "sort", "equal", "constantly", "subsequent", "equipment", "constant", "error", "especially", "briefly", "essential", 
    "establish", "still", "late", "frequent", "weekly", "evening", "event", "eventually", "prior", "sudden", "everybody", "routine", "everyone", "everything", "early", "evidence", "rapid", "continuous", "satisfaction", "exactly", "shell", "bone", "concrete", 
    "excellent", "except", "tooth", "important", "exchange", "possible", "brilliant", "wealthy", "executive", "exercise", "employment", "exist", "expand", "thick", "sick", "angry", "expensive", "nervous", "experiment", "sharp", "expert", "explain", "sufficient", 
    "export", "guilty", "old", "express", "expression", "fortunate", "already", "extent", "awareness", "extra", "weak", "sure", "extremely", "possession", "variable", "facility", "creative", "factor", "factory", "independence", "fail", "failure", "fair", "able", 
    "regional", "psychological", "mayor", "familiar", "tight", "famous", "fan", "upper", "top", "frequency", "farm", "way", "fashion", "fast", "enormous", "father", "people", "favor", "favorite", "feature", "federal", "fee", "notion", "female", "hypothesis", 
    "same", "whether", "reflection", "field", "fight", "next", "fill", "film", "significance", "final", "finally", "finance", "financial", "issue", "fine", "finger", "finish", "fire", "firm", "properly", "reasonably", "perfectly", "fish", "fit", "fix", "stable", 
    "well", "flat", "firmly", "flight", "successfully", "floor", "flow", "fly", "focus", "hopefully", "gently", "typically", "dramatically", "faithfully", "foot", "football", "automatically", "literally", "foreign", "forest", "significantly", "forget", "somehow", 
    "differently", "effectively", "furthermore", "former", "also", "equally", "forward", "precisely", "roughly", "rarely", "surprisingly", "freedom", "wherever", "against", "southern", "abroad", "fresh", "overseas", "friendly", "elsewhere", "northern", "front", 
    "partly", "there", "among", "full", "fully", "fun", "function", "primarily", "fund", "respectively", "funny", "at", "under", "least", "between", "how", "anywhere", "garden", "gas", "every", "gather", "grand", "comprehensive", "instruction", "database", 
    "general", "generate", "generation", "hint", "proof", "interior", "sake", "remarkable", "attraction", "gift", "girl", "if", "glad", "intervention", "glass", "global", "social", "goal", "theoretical", "gold", "product", "furniture", "profession", "evaluation", 
    "only", "maintenance", "spare", "grade", "piano", "gentle", "experience", "wise", "silly", "grant", "stupid", "shore", "coast", "estate", "big", "green", "wealth", "ocean", "ground", "long", "cow", "growth", "guarantee", "guess", "guest", "guide", 
    "substantial", "considerable", "guy", "hair", "extensive", "maximum", "handle", "permanent", "after", "happy", "discovery", "divorce", "hardly", "power", "ownership", "hate", "secondary", "pale", "comedy", "health", "healthy", "probably", "heart", 
    "heat", "medicine", "heavy", "menu", "catalog", "small", "somewhat", "alive", "around", "knife", "herself", "nerve", "tube", "hide", "valley", "highly", "rail", "himself", "mortgage", "tender", "minimum", "printer", "hit", "golden", "wooden", "hole", 
    "holiday", "prime", "implementation", "loud", "quietly", "reduction", "attractive", "person", "horse", "hospital", "hot", "multiple", "often", "fuel", "huge", "human", "capability", "dimension", "surgery", "husband", "letter", "salary", "compensation", 
    "identify", "deposit", "ignore", "evil", "increasingly", "several", "mom", "grandmother", "up", "immediately", "to", "promotion", "very", "strict", "salt", "together", "importance", "by", "impossible", "most", "vital", "thirst", "improve", "improvement", 
    "innovation", "close", "anymore", "silence", "illegal", "nothing", "unable", "indeed", "unlikely", "independent", "crazy", "within", "individual", "industry", "dirty", "open", "rare", "influence", "inform", "never", "initial", "unknown", "nearby", "bad", 
    "little", "innocent", "light", "away", "low", "inside", "badly", "nowhere", "confusion", "instance", "instead", "institution", "lazy", "few", "insurance", "pure", "different", "new", "intend", "fancy", "false", "rough", "minor", "internal", "international", 
    "silent", "ordinary", "thin", "interview", "loose", "introduce", "introduction", "occasionally", "invest", "investigate", "investigation", "investment", "ill", "invite", "one", "group", "island", "density", "age", "item", "itself", "he", "gradually", 
    "join", "monthly", "weird", "about", "democratic", "intellectual", "judge", "judgment", "jump", "brown", "qualification", "frequently", "fat", "right", "today", "key", "kid", "kill", "a", "any", "kitchen", "another", "again", "ski", "knowledge", 
    "labor", "planet", "lack", "land", "either", "once", "largely", "kind", "laugh", "almost", "launch", "law", "lay", "merely", "just", "liberal", "leader", "leadership", "electronic", "folk", "civilian", "charity", "supplier", "establishment", 
    "base", "left", "leg", "legal", "besides", "forth", "length", "yard", "external", "panic", "portrait", "pink", "library", "lie", "lift", "segment", "share", "likely", "limit", "portion", "link", "wing", "list", "listen", "mind", "neck", 
    "eye", "literature", "nose", "tongue", "load", "module", "location", "fragment", "emphasis", "ideal", "week", "gay", "immigrant", "loss", "hero", "peer", "lovely", "employer", "member", "substitute", "you", "lunch", "student", "machine", 
    "athlete", "magazine", "champion", "main", "mainly", "maintain", "governor", "major", "majority", "holder", "specialist", "male", "poet", "manage", "management", "manager", "manner", "manufacture", "friend", "map", "maker", "mark", "this", 
    "marriage", "marry", "personality", "match", "parent", "material", "injury", "illustration", "curtain", "flag", "skirt", "maybe", "tissue", "gate", "stomach", "measure", "center", "jail", "gallery", "medical", "home", "medium", "intention", 
    "program", "grass", "memory", "musical", "mention", "opera", "proud", "poetry", "tent", "message", "approval", "implication", "method", "middle", "vessel", "mile", "military", "passion", "mine", "conservative", "minister", "cost", "matter", 
    "formation", "publication", "mix", "recovery", "interaction", "market", "withdraw", "modern", "penalty", "justice", "humor", "beauty", "monitor", "charm", "darkness", "stability", "weakness", "moreover", "tendency", "scope", "mostly", "class", 
    "resistance", "state", "pension", "job", "emotional", "mountain", "mouth", "academic", "movement", "movie", "criminal", "scientific", "murder", "romantic", "museum", "clinical", "structural", "local", "racial", "myself", "rural", "educational", 
    "fundamental", "nation", "national", "presidential", "natural", "calm", "nature", "near", "inquiry", "nearly", "necessarily", "necessary", "honor", "permission", "high", "moon", "guideline", "neighbor", "grammar", "acceptable", "too", "network", 
    "complaint", "autumn", "news", "newspaper", "paragraph", "nice", "grain", "period", "nobody", "nor", "normal", "normally", "north", "religion", "system", "apartment", "mutual", "notice", "essay", "episode", "novel", "alongside", "plain", "aunt", 
    "nuclear", "mere", "town", "nurse", "object", "objective", "pocket", "stamp", "observe", "obvious", "obviously", "bit", "stream", "occur", "cap", "less", "cheek", "snow", "answer", "officer", "official", "part", "oil", "okay", "prisoner", "dealer", 
    "designer", "pro", "buyer", "politician", "slave", "operate", "operation", "shareholder", "opinion", "opportunity", "opposite", "listener", "option", "historian", "ally", "operator", "enemy", "organization", "volunteer", "mate", "otherwise", "ought", 
    "reporter", "stranger", "supplement", "variation", "problem", "outside", "other", "overall", "luxury", "achievement", "mixture", "impressive", "owner", "time", "pack", "page", "pain", "paint", "exception", "hat", "paper", "classic", "biological", 
    "disaster", "park", "burden", "participate", "incentive", "particular", "particularly", "smooth", "partner", "outcome", "pass", "composition", "priority", "path", "patient", "pattern", "pause", "fact", "payment", "peace", "preference", "compound", 
    "prize", "constraint", "indication", "obligation", "visual", "percent", "percentage", "perfect", "assumption", "perform", "performance", "perhaps", "thing", "pen", "rather", "personal", "tone", "alarm", "music", "perspective", "representation", 
    "celebration", "ceremony", "phone", "photo", "gear", "physical", "rate", "pick", "picture", "piece", "championship", "from", "ease", "gender", "attendance", "existence", "comfort", "exposure", "plane", "happiness", "plant", "complexity", 
    "diversity", "stair", "player", "tale", "please", "pleasure", "plus", "side", "guitar", "attachment", "barrier", "philosophy", "police", "history", "mathematics", "politics", "dramatic", "flash", "pool", "poor", "pop", "popular", "formal", 
    "number", "lecture", "position", "positive", "sweet", "examination", "possibility", "exam", "possibly", "post", "potentially", "concentration", "potential", "imagination", "pound", "selection", "entry", "immigration", "powerful", "practice", 
    "bath", "shower", "east", "measurement", "predict", "prefer", "chest", "outline", "king", "meat", "unemployment", "prepare", "ear", "half", "I", "prospect", "press", "pressure", "discipline", "narrative", "pretty", "prevent", "previous", 
    "previously", "peak", "diet", "self", "primary", "consequently", "string", "wire", "book", "anything", "private", "something", "brush", "view", "clothing", "careful", "future", "procedure", "proceed", "pregnancy", "produce", "retirement", 
    "production", "night", "deeply", "submit", "profit", "acknowledge", "progress", "project", "promise", "promote", "pretend", "behave", "help", "proper", "do", "proposal", "propose", "process", "protect", "protection", "crack", "seem", "prove", 
    "question", "bless", "spell", "can", "live", "attach", "feel", "pull", "hear", "purchase", "exceed", "purpose", "sit", "push", "remain", "differ", "regret", "quality", "result", "quarter", "lose", "quick", "quickly", "quiet", "need", "stand", 
    "quote", "freeze", "recover", "radio", "disappear", "rain", "raise", "undertake", "range", "become", "arise", "react", "expect", "reckon", "lean", "burst", "split", "sigh", "remember", "import", "reaction", "construct", "reader", "insure", 
    "reality", "realize", "love", "send", "embarrass", "reasonable", "move", "recall", "convert", "recent", "recently", "update", "adapt", "recognize", "recommend", "transform", "translate", "edit", "red", "reduce", "wipe", "refer", "reference", 
    "shut", "reform", "integrate", "refuse", "regard", "follow", "return", "register", "reach", "meet", "regular", "cluster", "compose", "regulation", "relate", "relationship", "relative", "relatively", "eliminate", "retain", "religious", "drive", 
    "wrap", "make", "invent", "remind", "cope", "remove", "rent", "devote", "repeat", "replace", "reply", "want", "price", "representative", "request", "require", "requirement", "weigh", "research", "grow", "resident", "derive", "control", "detect", 
    "find", "consult", "exhibit", "resource", "respect", "play", "respond", "response", "responsibility", "responsible", "rest", "restaurant", "fulfill", "rush", "use", "continue", "begin", "solar", "consume", "be", "anticipate", "reveal", "revenue", 
    "undergo", "review", "show", "praise", "protest", "neglect", "rich", "admire", "ride", "occupy", "rise", "risk", "river", "road", "rock", "role", "roll", "resolve", "calculate", "root", "compute", "like", "round", "route", "trace", "stop", "repair", 
    "rule", "study", "specialize", "chase", "safe", "safety", "pursue", "cough", "evaluate", "poll", "learn", "recruit", "buy", "receive", "deserve", "satisfy", "save", "qualify", "scale", "persuade", "excuse", "scene", "schedule", "scheme", "communicate", 
    "support", "science", "pay", "deal", "score", "justify", "screen", "sea", "assign", "search", "season", "reward", "offer", "entitle", "section", "sector", "secure", "lend", "yield", "seek", "dedicate", "sink", "select", "reverse", "accompany", "sell", 
    "visit", "senior", "sense", "develop", "sentence", "separate", "distribute", "series", "serious", "give", "serve", "disagree", "negotiate", "settle", "mean", "think", "keep", "sex", "dare", "know", "shake", "shall", "shape", "involve", "encounter", 
    "possess", "dominate", "correspond", "assist", "boost", "sponsor", "shift", "crash", "ship", "shock", "shoot", "shop", "tap", "short", "knock", "embrace", "harm", "incorporate", "point", "unite", "isolate", "preserve", "understand", "significant", 
    "resign", "abandon", "allow", "underlie", "counsel", "similar", "simple", "simply", "care", "sing", "single", "read", "watch", "sister", "stare", "glance", "situation", "size", "scan", "skill", "fade", "service", "sleep", "sustain", "alter", "decide", 
    "slightly", "boom", "pour", "slow", "swear", "scream", "bet", "smoke", "try", "provide", "shine", "craft", "society", "revise", "software", "note", "soldier", "complicate", "solution", "solve", "change", "somebody", "increase", "someone", "regulate", 
    "sometimes", "impress", "somewhere", "son", "song", "frighten", "sorry", "trick", "motivate", "source", "south", "scare", "space", "depress", "inspire", "speaker", "special", "anger", "bore", "interest", "specific", "speech", "speed", "include", 
    "enhance", "stretch", "spirit", "cause", "ban", "sport", "spot", "spread", "spring", "bend", "seal", "staff", "stage", "trigger", "strengthen", "confuse", "assure", "level", "standard", "star", "constitute", "comprise", "pump", "statement", 
    "station", "status", "create", "stain", "step", "stick", "greet", "suggest", "cite", "stone", "stir", "breathe", "store", "wander", "leap", "straight", "dig", "strange", "fold", "strategy", "put", "street", "strength", "go", "stress", "hurry", 
    "slide", "strike", "swing", "come", "walk", "strong", "run", "struggle", "owe", "rid", "stuff", "disappoint", "let", "perceive", "distinguish", "get", "appoint", "success", "successful", "govern", "mount", "suddenly", "suffer", "have", "call", 
    "take", "suggestion", "suit", "situate", "sum", "click", "summer", "sun", "bite", "restrict", "supply", "exclude", "suppose", "breed", "defend", "surface", "input", "surprise", "restore", "surround", "survey", "pose", "survive", "place", "bury", 
    "grab", "borrow", "sweep", "swim", "interpret", "rescue", "remark", "table", "value", "tell", "joke", "blame", "damn", "declare", "apologize", "accuse", "tape", "target", "task", "tax", "taxi", "tea", "teach", "teacher", "team", "technical", 
    "technique", "telephone", "criticize", "talk", "tend", "ask", "steal", "broadcast", "dismiss", "cast", "break", "install", "expose", "lead", "slip", "text", "evolve", "grin", "shout", "ruin", "theater", "theme", "themselves", "implement", 
    "found", "summarize", "allege", "therefore", "specify", "float", "cancel", "hesitate", "disturb", "suspend", "retire", "threat", "threaten", "emphasize", "throughout", "throw", "thus", "ticket", "urge", "till", "analyze", "win", "tire", 
    "overcome", "title", "accomplish", "collapse", "imply", "tomorrow", "advise", "tackle", "tonight", "entertain", "bring", "happen", "topic", "total", "totally", "tough", "tour", "tourist", "strip", "toward", "bother", "chat", "whisper", 
    "track", "trade", "traditional", "traffic", "educate", "thank", "transfer", "aside", "consider", "transport", "believe", "travel", "treat", "treatment", "tree", "trend", "trial", "stroke", "sail", "trip", "trouble", "resist", "compete", 
    "trust", "truth", "spin", "twist", "look", "twice", "figure", "hold", "spend", "typical", "force", "say", "speak", "see", "smell", "march", "unclear", "defeat", "pray", "strain", "soil", "head", "rear", "unfortunately", "journey", "unique", 
    "unit", "therapy", "upset", "van", "university", "pipe", "unless", "twin", "ratio", "vice", "climate", "blind", "raw", "upon", "beneath", "illness", "word", "meter", "year", "useful", "usual", "usually", "minute", "ugly", "yet", "until", 
    "could", "but", "various", "vary", "ourselves", "vehicle", "everyday", "actually", "version", "with", "might", "secondly", "should", "or", "some", "the", "video", "we", "village", "they", "and", "both", "must", "without", "versus", 
    "visitor", "for", "that", "voice", "volume", "may", "than", "vote", "wait", "will", "wall", "functional", "electric", "war", "warm", "warn", "wash", "waste", "digital", "wave", "experimental", "train", "really", "precise", "mad", 
    "terrible", "weapon", "awful", "severe", "weekend", "massive", "fantastic", "weight", "great", "welcome", "extreme", "greatly", "radical", "ancient", "newly", "whatever", "moment", "parallel", "slight", "whereas", "steel", "intense", 
    "horrible", "tiny", "quite", "white", "form", "curious", "competitive", "wide", "sound", "wife", "wild", "mode", "yes", "wind", "window", "wine", "custom", "winter", "who", "food", "name", "wish", "probability", "hello", "hi", 
    "excitement", "wonder", "wonderful", "invitation", "pregnant", "youth", "worker", "pride", "worry", "worth", "hope", "boundary", "wrong", "rice", "yeah", "sugar", "determination", "cable", "yesterday", "surely", "rapidly", "regardless", 
    "not", "yourself", "verb", "when", "where", "candidate", "language", "conference", "efficiency", "partnership", "valuable", "criticism", "own"
    ]
#NGSL 1.2 List used and https://arraythis.com/ to create the list
#list3 = ["x", "y", "z"]

# Step 2: Get user input for the reading passage/ academic text
print("")
print ("Welcome to ESL Vocabulary Checker. Currently with version 1, your text can be checked with NAWL and NGSL.")
print("=======================================================================================================")
print("")
print("The NAWL list is a 957 word list of the most important words for general academic English.")
print("=======================================================================================================")
print("")
print("The NGSL list is a 2809-word list of the most important words of general English and daily life for second language learners.")
print("It is less than 10 percent of the vocabulary known by native speaker college graduates, but gives an average of 92 percent of most texts of general English and even higher coverage in other situates.")
print("For example: 93 percent coverage of Harry Potter, 94 percent for TOEIC exams, etc.")
print("=======================================================================================================")
print("")
print("")
reading_passage = input("Please enter a reading passage or academic text: ")

# Step 3: Scan the input and check for matches
# Convert the input to a list of words (split by whitespace)
words_in_passage = reading_passage.split()

# Initialize sets to store matching words from each list
matches_NAWL = set()
matches_NGSL = set()
#matches_list3 = set()

# Check for matches in each list
for word in words_in_passage:
    if word in NAWL:
        matches_NAWL.add(word)
    if word in NGSL:
        matches_NGSL.add(word)
    #if word in list3:
        #matches_list3.add(word)

# Step 4: Output the matching words to the user
print("")
if matches_NAWL:
    print(f"Words from NAWL that match: {', '.join(matches_NAWL)}")
    print("")
else:
    print("No words from NAWL matched.")
    print("")

if matches_NGSL:
    print(f"Words from NGSL that match: {', '.join(matches_NGSL)}")
    print("")
else:
    print("No words from NGSL matched.")
    print("")

#if matches_list3:
    #print(f"Words from list 3 that match: {', '.join(matches_list3)}")
#else:
#    print("No words from list 3 matched.")

#Print ending text
print("Thank you for using my vocabulary checker! In the future I hope to update it to allow advanced syntaxt checking, vocabulary frequency numbers, an option to give easy definitions, add a third list for it to check, and have it export matched words into an excel sheet.")